package com.schoolsystem.project.domains;

public enum SubjectType {
	MATH, CHEMISTRY, PHYSICS, BIOLOGY, CIVICS, ENGLISH, AMHARIC, GEOGRAPHY, HISTORY, COMMUNICATION,
	PHYSICAL_EDUCTAION, ECONOMICS, MANAGEMENT, ART, MUSIC, SAT
}
